# Generated by Django 4.1.13 on 2024-05-08 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fanlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Kunlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchituvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterKurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('familya', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('izoh', models.TextField()),
                ('dars_kunlari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanlar.kunlar')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fanlar.fanlar')),
            ],
        ),
        migrations.AddField(
            model_name='fanlar',
            name='oqituvchi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oqituvchi', to='fanlar.oquvchituvchilar'),
        ),
    ]
